redis:
  host: "localhost"
  port: "6379"
  password: ""
  indices: "0-5"
  key_prefix: "" #can be empty
  timeout: 5

server:
  host: "localhost"
  port: "8080"
  mode: "test" # can be "release", "debug" or "test". default is "release"
  timeout:
    read: 5
    write: 10
    idle: 120
    read_header: 2
  tls: 
    enabled: false
    cert_file: "cert.pem"
    key_file: "key.pem"
    client_certs: "client_certs.pem"


config:
  hash_keys: true

admin:
  enabled: true
  jwt_secret: "your-super-secret-jwt-key-change-in-production"
  allowed_ips: ["127.0.0.1", "::1"]  # Add your allowed IPs here
  basic_auth: false    # Use JWT auth instead of basic auth
  require_auth: true   # Set to false for development (NOT recommended for production)

