# docker-compose.yaml for OTP Service

services:
  otp-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: otp-service
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - otp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped
    networks:
      - otp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M

networks:
  otp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
