# docker-compose.yaml for OTP Service

services:
  otp-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: otp-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_INDICES=0-5
      - REDIS_KEY_PREFIX=${REDIS_KEY_PREFIX:-}
      - REDIS_TIMEOUT=5
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_MODE=test
      - HASH_KEYS=true
      # Admin configuration for Docker
      - ADMIN_ENABLED=true
      - ADMIN_JWT_SECRET=docker-dev-jwt-secret-change-in-production
      - ADMIN_BASIC_AUTH=false
      - ADMIN_REQUIRE_AUTH=false  # Disable auth in Docker test mode
      - ADMIN_ALLOWED_IPS=127.0.0.1,::1,172.20.0.1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - otp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  redis:
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - otp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M

  # Optional: Redis monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    ports:
      - "9121:9121"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - otp-network
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local

networks:
  otp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
