# Prometheus Configuration for OTP Service Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'otp-service-cluster'
    environment: 'production'

# Rule files
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # OTP Service metrics
  - job_name: 'otp-service'
    static_configs:
      - targets: 
          - 'otp-service:9090'
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # HAProxy stats
  - job_name: 'haproxy'
    static_configs:
      - targets: ['load-balancer:8404']
    scrape_interval: 30s
    metrics_path: '/stats/prometheus'
    scrape_timeout: 5s

  # Node Exporter (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB